'use client';

import DailyBriefContent from '@/components/daily-brief/DailyBriefContent';
import { Sun, Info } from 'lucide-react';

export default function DailyBriefPage() {
  const today = new Date().toLocaleDateString('en-IN', {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
      {/* Page Header */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-3">
          <div className="w-10 h-10 bg-orange-500 rounded-xl flex items-center justify-center">
            <Sun className="w-5 h-5 text-white" />
          </div>
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold text-gray-900">
              Daily Brief
            </h1>
            <p className="text-sm text-gray-500">
              {today}
            </p>
          </div>
        </div>

        {/* How it works */}
        <div className="bg-orange-50 border border-orange-100 rounded-xl p-4 mt-4">
          <div className="flex items-start gap-2">
            <Info className="w-5 h-5 text-orange-600 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-sm text-orange-800 font-medium mb-1">
                Your Daily Distributor Companion
              </p>
              <p className="text-xs text-orange-600 leading-relaxed">
                Start your day with AI-curated insights designed specifically for mutual fund distributors.
                Get the top stories affecting your clients, ready-to-use conversation starters,
                and prioritized action items. Everything is framed to help you serve your clients better,
                not as investment advice. Brief is refreshed daily.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Daily Brief Content */}
      <DailyBriefContent />

      {/* Bottom Disclaimer */}
      <div className="mt-8 bg-gray-50 border border-gray-200 rounded-lg p-4">
        <p className="text-[11px] text-gray-500 leading-relaxed">
          <strong>Disclaimer:</strong> This daily brief is generated by AI and is intended
          for mutual fund distributors as a preparatory tool only. It does not constitute
          investment advice or recommendations. Distributors should use their own judgment
          and conduct their own research when advising clients. Always ensure recommendations
          are suitable for each client&apos;s individual circumstances and risk profile.
          Mutual fund investments are subject to market risks. Please read all scheme-related
          documents carefully before advising clients.
        </p>
      </div>
    </div>
  );
}
