'use client';

import NewsFeed from '@/components/news/NewsFeed';
import { Newspaper, Info } from 'lucide-react';

export default function NewsPage() {
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
      {/* Page Header */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-3">
          <div className="w-10 h-10 bg-blue-600 rounded-xl flex items-center justify-center">
            <Newspaper className="w-5 h-5 text-white" />
          </div>
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold text-gray-900">
              News Insights
            </h1>
            <p className="text-sm text-gray-500">
              What today&apos;s news means for your HDFC mutual fund investments
            </p>
          </div>
        </div>

        {/* How it works */}
        <div className="bg-blue-50 border border-blue-100 rounded-xl p-4 mt-4">
          <div className="flex items-start gap-2">
            <Info className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-sm text-blue-800 font-medium mb-1">
                How News Insights Works
              </p>
              <p className="text-xs text-blue-600 leading-relaxed">
                We aggregate news from India&apos;s top financial sources
                (Economic Times, Moneycontrol, Livemint), then use AI to analyze
                each story&apos;s impact on HDFC Mutual Fund schemes. Each
                insight tells you which funds may be affected and what you should
                consider as a long-term investor. News is refreshed every 4
                hours.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* News Feed */}
      <NewsFeed />

      {/* Bottom Disclaimer */}
      <div className="mt-8 bg-gray-50 border border-gray-200 rounded-lg p-4">
        <p className="text-[11px] text-gray-500 leading-relaxed">
          <strong>Disclaimer:</strong> News insights are generated by AI and
          are for educational purposes only. They do not constitute investment
          advice. News analysis may not capture all nuances. Always verify
          information from multiple sources before making investment decisions.
          Mutual fund investments are subject to market risks. Please consult a
          SEBI-registered investment advisor for personalized advice.
        </p>
      </div>
    </div>
  );
}
