'use client';

import { useState, useEffect } from 'react';
import { track } from '@vercel/analytics';
import MondayBriefDocument from '@/components/monday-brief/MondayBriefDocument';
import { Calendar, Info, Printer } from 'lucide-react';

export default function MondayBriefPage() {
  const [lang, setLang] = useState<'en' | 'hi'>('en');

  useEffect(() => {
    track('monday_brief_viewed');
  }, []);

  const now = new Date();
  // Find this week's Monday
  const day = now.getDay();
  const diff = day === 0 ? -6 : 1 - day;
  const monday = new Date(now);
  monday.setDate(now.getDate() + diff);
  const friday = new Date(monday);
  friday.setDate(monday.getDate() + 4);

  const fmt = (d: Date) =>
    d.toLocaleDateString('en-IN', { day: 'numeric', month: 'long' });
  const weekRange = `${fmt(monday)} - ${fmt(friday)}, ${friday.getFullYear()}`;

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
      {/* Page Header */}
      <div className="mb-8 no-print">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-[#e31e24] rounded-xl flex items-center justify-center">
              <Calendar className="w-5 h-5 text-white" />
            </div>
            <div>
              <h1 className="text-2xl sm:text-3xl font-bold text-gray-900">
                Monday Morning Brief
              </h1>
              <p className="text-sm text-gray-500">
                Week of {weekRange}
              </p>
            </div>
          </div>

          {/* Hindi / English toggle */}
          <button
            onClick={() => {
              const next = lang === 'en' ? 'hi' : 'en';
              track('monday_brief_lang_toggle', { language: next });
              setLang(next);
            }}
            className="inline-flex items-center gap-2 border border-gray-300 text-gray-700 px-4 py-2 rounded-lg hover:bg-gray-50 transition-colors text-sm font-medium"
            title={lang === 'en' ? 'हिन्दी में देखें' : 'View in English'}
          >
            <span className="text-base">{lang === 'en' ? '🇮🇳' : '🇬🇧'}</span>
            {lang === 'en' ? 'हिन्दी' : 'English'}
          </button>
        </div>

        {/* Info box */}
        <div className="bg-red-50 border border-red-100 rounded-xl p-4 mt-4">
          <div className="flex items-start gap-2">
            <Info className="w-5 h-5 text-[#e31e24] flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-sm text-red-900 font-medium mb-1">
                {lang === 'hi' ? 'आपकी साप्ताहिक प्रीमियम पुस्तिका' : 'Your Premium Weekly Playbook'}
              </p>
              <p className="text-xs text-red-700 leading-relaxed">
                {lang === 'hi'
                  ? 'इस सप्ताह के ग्राहक संवाद के लिए सब कुछ एक प्रिंट-रेडी दस्तावेज़ में। बाज़ार का संदर्भ, मुख्य खबरें, कार्य योजना, बातचीत की स्क्रिप्ट, और आने वाले सप्ताह का रडार। AI-निर्मित — ग्राहकों से बात करने से पहले बाज़ार डेटा सत्यापित करें।'
                  : 'Everything you need for client conversations this week in one print-ready document. Market context, top stories with talking points, a full action plan, conversation scripts for 3 client personas, star fund highlights, and a week-ahead radar. AI-generated — verify market data before client calls.'}
              </p>
            </div>
          </div>
        </div>

        {/* Download PDF button */}
        <div className="mt-4 flex justify-end">
          <button
            onClick={() => { track('monday_brief_printed', { language: lang }); window.print(); }}
            className="inline-flex items-center gap-2 bg-[#e31e24] text-white px-5 py-2.5 rounded-lg hover:bg-red-700 transition-colors text-sm font-medium shadow-sm"
          >
            <Printer className="w-4 h-4" />
            {lang === 'hi' ? 'PDF डाउनलोड करें' : 'Download PDF'}
          </button>
        </div>
      </div>

      {/* Monday Brief Document */}
      <MondayBriefDocument lang={lang} />

      {/* Bottom Disclaimer */}
      <div className="mt-8 bg-gray-50 border border-gray-200 rounded-lg p-4 no-print">
        <p className="text-[11px] text-gray-500 leading-relaxed">
          <strong>Disclaimer:</strong> This Monday Morning Brief is generated by AI and is intended
          for mutual fund distributors as a preparatory tool only. It does not constitute
          investment advice or recommendations. Distributors should use their own judgment
          and conduct their own research when advising clients. Always ensure recommendations
          are suitable for each client&apos;s individual circumstances and risk profile.
          Mutual fund investments are subject to market risks. Please read all scheme-related
          documents carefully before advising clients. Past performance is not indicative of
          future results.
        </p>
      </div>
    </div>
  );
}
